# Generated by Django 6.0.6 on 2026-06-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('donor_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
            ],
        ),
    ]
