# Generated by Django 6.0.6 on 2026-06-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_fooddonation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddonation',
            name='phone',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
