# Generated by Django 6.0.6 on 2026-06-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_foodrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddonation',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Requested', 'Requested'), ('Collected', 'Collected')], default='Available', max_length=20),
        ),
    ]
