# Generated by Django 6.0.6 on 2026-06-24 17:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_alter_fooddonation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddonation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fooddonation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fooddonation',
            name='food_type',
            field=models.CharField(default='Veg', max_length=50),
        ),
        migrations.AddField(
            model_name='fooddonation',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fooddonation',
            name='receiver_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
