# Generated by Django 6.0.6 on 2026-06-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_fooddonation_created_at_fooddonation_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddonation',
            name='food_image',
            field=models.ImageField(blank=True, null=True, upload_to='food_images/'),
        ),
    ]
